apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: t4jsd8z9g-go
  janus-idp.io/tekton: t4jsd8z9g-go
  backstage.io/kubernetes-id: t4jsd8z9g-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: t4jsd8z9g-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
